services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: cbc_iii_frontend

    ports:
      - "4200:4200"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - strapi

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped

  strapi:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: cbc_iii_strapi

    ports:
      - "1337:1337"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app
      - /app/node_modules

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped